let shopSupervision=shops.map(()=>AdminModel.initial()),productSupervision={},adminRecords=[];
let adminCatalog=new Map(products.map(p=>[p.id,p]));
function productControl(id){return productSupervision[id]||(productSupervision[id]=AdminModel.initial());}
function refreshAdminCatalog(){for(const p of products)adminCatalog.set(p.id,p);}
function applyAdminVisibility(){refreshAdminCatalog();for(let i=products.length-1;i>=0;i--){const p=products[i],s=productControl(p.id),own=createdProducts.find(x=>x.productId===p.id);if(shopSupervision[p.shop].stopped||s.blocked||!s.listed||own?.deleted||own&&own.status!=='在售')products.splice(i,1);}for(const [id,p] of adminCatalog){const s=productControl(id),own=createdProducts.find(x=>x.productId===id);if(!products.some(x=>x.id===id)&&!shopSupervision[p.shop].stopped&&!s.blocked&&s.listed&&!own?.deleted&&(!own||own.status==='在售'))products.push(p);}cart=cart.filter(r=>products.some(p=>p.id===r.id));updateCartIndicator();resetSelection();reflectStock();render();}
function adminLog(scope,id,action,reason){adminRecords.unshift({scope,id,action,reason,time:new Date().toLocaleString('zh-CN')});}
function adminDisposition(scope,id,action,reason,reportId){refreshAdminCatalog();const report=reportId?demoReports.find(r=>r.id===reportId):null;if(reportId&&report?.status!=='待处理')throw Error('举报已处理或不存在');let next;if(action!=='clear'){const state=scope==='shop'?shopSupervision[id]:productControl(id);next=AdminModel.act(state,action,reason);}else if(!reason.trim())throw Error('请填写处理说明');if(report&&scope==='product'&&(report.target.shop!==adminCatalog.get(+id)?.shop))throw Error('处理商品必须属于举报店铺');if(next){if(scope==='shop')shopSupervision[id]=next;else productSupervision[id]=next;}if(action==='emergency'){const own=createdProducts.find(p=>p.productId===+id);if(own){own.status='已下架';own.offReason='管理员紧急下架';}}if(action==='stop'){for(const o of [...demoOrders])if(o.shop===+id&&o.status==='待付款')walletTransaction([o.id],'cancel');}if(report){report.status='已处理';report.result=adminActionLabel(action)+'：'+reason.trim();report.resolvedAt=new Date().toLocaleString('zh-CN');}adminLog(scope,id,adminActionLabel(action),reason.trim());applyAdminVisibility();}
function adminActionLabel(a){return {warn:'警告商家',stop:'暂停营业',emergency:'紧急下架',clear:'未发现违规',approve:'审核通过',reject:'审核驳回',request:'提交整改申请'}[a]||a;}
const adminSyncBase=syncPublishedProduct;syncPublishedProduct=function(p){if(p.status==='在售'&&(shopSupervision[0].stopped||(p.productId&&productControl(p.productId).blocked)||p.deleted)){toast('店铺停业或商品存在独立限制，不能上架');return;}adminSyncBase(p);if(p.productId){const live=products.find(x=>x.id===p.productId);if(live)adminCatalog.set(p.productId,live);productControl(p.productId).listed=p.status==='在售';}};
const adminRemoveBase=removeFromSale;removeFromSale=function(p,reason){if(p.productId)productControl(p.productId).listed=false;adminRemoveBase(p,reason);};
const adminSaveBase=saveEditedProduct;saveEditedProduct=function(publish){if((publish||productDraft.status==='在售')&&(shopSupervision[0].stopped||(productDraft.productId&&productControl(productDraft.productId).blocked))){$('editorErrors').textContent='店铺停业或商品被紧急下架，须审核解除限制后才能上架；可先保存草稿。';return;}adminSaveBase(publish);};
const adminDetailBase=showProductDetail;showProductDetail=function(p){if(!p||!products.some(x=>x.id===p.id)){toast('商品当前不可购买');return;}adminDetailBase(p);};
const adminRenderBase=render;render=function(){adminRenderBase();if(route==='store'&&shopSupervision[storeId]?.stopped){$('subtitle').textContent='店铺已暂停营业，暂不展示商品或接受新订单。';$('list').innerHTML='<div class="empty"><h3>暂停营业</h3><p>已付款订单仍正常履约。</p></div>';}document.querySelectorAll('.store [data-store]').forEach(b=>{if(shopSupervision[+b.dataset.store]?.stopped)b.insertAdjacentHTML('beforebegin','<p class="tag">暂停营业</p>');});};
const adminWalletBase=walletTransaction;walletTransaction=function(ids,action,reason){if(action==='pay'&&ids.some(id=>shopSupervision[demoOrders.find(o=>o.id===id)?.shop]?.stopped))throw Error('店铺已暂停营业，不能付款');adminWalletBase(ids,action,reason);};
const adminReportDetailBase=reportDetail;reportDetail=function(id){adminReportDetailBase(id);if($('simulateReport')){$('simulateReport').textContent='进入管理员处理预览';$('simulateReport').onclick=()=>adminReportReview(id);}};
