const $=id=>document.getElementById(id);
const names=['随行保温杯','方格手账本','帆布日常托特包','轻量桌面台灯','无线便携鼠标','柔软棉质短袖','阅读与远方','晴雨折叠伞','简约陶瓷马克杯','舒适运动袜','桌面收纳盒','复古胶片相机'];
const icons=['🥤','📒','👜','💡','🖱️','👕','📚','☂️','☕','🧦','🗃️','📷'];
const colors=['#e9eddf','#eee8da','#e4e9e3','#ede6d9','#e0e7e9','#ebe0dc'];
const shops=['青禾生活小店','同学的杂货铺','晚风工作室','拾光校园店'];
const products=Array.from({length:60},(_,i)=>({id:i+1,name:names[i%12]+(i>=12?' · '+['晨光','原野','雾白','暮色'][Math.floor(i/12)-1]:''),shop:i%4,sales:(i*137+29)%920,icon:icons[i%12],bg:colors[i%6],defaultVariant:0,variants:[{name:'标准款',price:12+(i*7)%120,stock:i%13===0?0:20},{name:'升级款',price:22+(i*7)%120,stock:10}]}));
let route='home',tab='products',keyword='',page=1,pageSize=12,sort='default',selected={ids:[],anchor:null},cart=[],history=[],storeId=null;
let visible=[];const money=n=>'¥'+n.toFixed(2);const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function resetSelection(){selected={ids:[],anchor:null};}
function snapshot(){return {route,tab,keyword,page,pageSize,sort,storeId};}
function navigate(next){history.push(snapshot());route=next;page=1;storeId=null;resetSelection();render();}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4200);}
function results(){let data=products.filter(p=>(route!=='store'||p.shop===storeId)&&(route!=='search'||p.name.includes(keyword)||shops[p.shop].includes(keyword)));
 const compare={priceUp:(a,b)=>a.variants[0].price-b.variants[0].price,priceDown:(a,b)=>b.variants[0].price-a.variants[0].price,salesUp:(a,b)=>a.sales-b.sales,salesDown:(a,b)=>b.sales-a.sales};return compare[sort]?data.sort(compare[sort]):data;}
function render(){
 $('searchPanel').hidden=route!=='search';$('title').textContent=route==='home'?'把校园生活，装进购物车。':route==='store'?shops[storeId]:'想找的好物，就在这里。';
 $('subtitle').textContent=route==='home'?'发现身边的好物，逛逛同学们的小店。':route==='store'?'欢迎进店，看看今天有什么新发现。':'搜索商品或店铺，发现更多校园好物。';
 $('query').value=keyword;$('sort').value=sort;$('back').disabled=!history.length;
 document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 const isShops=route==='search'&&tab==='shops';const all=isShops?shops.map((name,id)=>({id,name})).filter(s=>s.name.includes(keyword)):results();
 const pages=Math.max(1,Math.ceil(all.length/pageSize));page=Math.min(page,pages);visible=all.slice((page-1)*pageSize,page*pageSize);
 $('sortWrap').hidden=isShops;$('resultTitle').textContent=isShops?'店铺搜索':route==='search'?'商品搜索结果':route==='store'?'店内商品':'全部商品';$('total').textContent=`${all.length} ${isShops?'家店铺':'件好物'}`;
 $('list').innerHTML=visible.length?visible.map(p=>isShops?`<article class="store"><span class="tag">校园店铺</span><h3>${p.name}</h3><p>生活好物，自在挑选</p><button data-store="${p.id}">进店逛逛 →</button></article>`:card(p)).join(''):'<div class="empty">没有找到相关结果，试试其他关键词。</div>';
 $('list').scrollTop=0;$('pageInfo').textContent=`共 ${all.length} ${isShops?'家店铺':'件商品'} · 第 ${page} / ${pages} 页`;
 $('prev').disabled=page<=1;$('next').disabled=page>=pages;$('pages').innerHTML=Array.from({length:pages},(_,i)=>`<button data-page="${i+1}" class="${page===i+1?'active':''}">${i+1}</button>`).join('');updateSelection();
}
function card(p){const v=p.variants[0];return `<article class="product" data-id="${p.id}" tabindex="0" aria-label="${p.name}" aria-selected="false"><span class="tick">✓</span><div class="art" style="--bg:${p.bg}"><div class="object">${p.icon}</div></div><div class="info"><h3>${p.name}</h3><button class="shopLink" data-store="${p.shop}">${shops[p.shop]} ↗</button><div class="bottom"><span class="price"><small>¥ </small>${v.price.toFixed(2)}</span><span class="sales">已售 ${p.sales}</span></div><div class="variant">${v.name}${v.stock===0?' · 默认规格暂时缺货':''}</div></div></article>`;}
function updateSelection(){document.querySelectorAll('[data-id]').forEach(el=>{const yes=selected.ids.includes(+el.dataset.id);el.classList.toggle('selected',yes);el.setAttribute('aria-selected',yes);});$('selectionText').textContent=selected.ids.length?`已选 ${selected.ids.length} 件商品 · 右键加入购物车`:'点击选择 · Shift 连选 · Ctrl 多选 · 双击查看详情';$('clear').disabled=!selected.ids.length;}
function add(ids){const result=ShopModel.addToCart(cart,ids.map(id=>products.find(p=>p.id===id)));cart=result.cart;updateCartIndicator();toast(`已加入 ${ids.length-result.skipped.length} 件商品${result.skipped.length?'；默认规格缺货或库存不足，跳过：'+result.skipped.map(id=>products.find(p=>p.id===id).name).join('、'):''}`);}
function modal(title,html){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;if(!$('dialog').open)$('dialog').showModal();}
function showCart(){modal('购物车',cart.length?cart.map((r,i)=>{const p=products.find(p=>p.id===r.id);return `<div class="cartRow"><span style="font-size:35px">${p.icon}</span><div class="content"><strong>${p.name}</strong><div><select data-variant="${i}" aria-label="${p.name}规格">${p.variants.map((v,j)=>`<option value="${j}" ${j===r.variant?'selected':''} ${v.stock<r.quantity?'disabled':''}>${v.name} · ${money(v.price)}${v.stock<r.quantity?' · 库存不足':''}</option>`).join('')}</select></div><span class="muted">数量 ${r.quantity} · 库存 ${p.variants[r.variant].stock}</span></div><strong>${money(p.variants[r.variant].price*r.quantity)}</strong><button data-remove="${i}">移除</button></div>`;}).join('')+`<p style="text-align:right;margin-top:20px">合计 <strong>${money(cart.reduce((n,r)=>n+products.find(p=>p.id===r.id).variants[r.variant].price*r.quantity,0))}</strong></p><p class="muted">本阶段演示商品选择与购物车规格修改。</p>`:'<div class="empty">购物车还是空的<br>选择一些好物，右键加入购物车。</div>');}
$('list').onclick=e=>{const shop=e.target.closest('[data-store]');if(shop){history.push(snapshot());route='store';storeId=+shop.dataset.store;page=1;resetSelection();render();return;}const row=e.target.closest('[data-id]');if(row){selected=ShopModel.select(selected,+row.dataset.id,visible.map(p=>p.id),e);updateSelection();}};
$('list').ondblclick=e=>{if(e.target.closest('[data-store]'))return;const row=e.target.closest('[data-id]');if(!row)return;const p=products.find(p=>p.id===+row.dataset.id);modal(p.name,`<div class="art" style="--bg:${p.bg};height:200px"><span class="object">${p.icon}</span></div><p>${shops[p.shop]} · 已售 ${p.sales}</p><p>默认规格：${p.variants[0].name} · ${money(p.variants[0].price)}</p><button class="primary" id="detailAdd">加入购物车</button>`);$('detailAdd').onclick=()=>add([p.id]);};
$('list').oncontextmenu=e=>{const row=e.target.closest('[data-id]');if(!row)return;e.preventDefault();const id=+row.dataset.id;if(!selected.ids.includes(id)){selected={ids:[id],anchor:id};updateSelection();}$('addSelected').textContent=`加入购物车（${selected.ids.length} 件商品）`;$('context').hidden=false;$('context').style.left=Math.min(e.clientX,innerWidth-250)+'px';$('context').style.top=Math.min(e.clientY,innerHeight-60)+'px';};
$('addSelected').onclick=()=>add(selected.ids);document.addEventListener('click',()=>$('context').hidden=true);document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('context').hidden=true;resetSelection();updateSelection();}});
$('searchEntry').onclick=()=>{navigate('search');$('query').focus();};$('home').onclick=()=>{keyword='';navigate('home');};$('back').onclick=()=>{const s=history.pop();if(!s)return;({route,tab,keyword,page,pageSize,sort,storeId}=s);resetSelection();render();};
$('searchForm').onsubmit=e=>{e.preventDefault();keyword=$('query').value.trim();page=1;resetSelection();render();};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;keyword=$('query').value.trim();page=1;resetSelection();render();});
$('sort').onchange=e=>{sort=e.target.value;page=1;resetSelection();render();};$('pageSize').onchange=e=>{pageSize=+e.target.value;page=1;resetSelection();render();};function turn(n){page=n;resetSelection();render();} $('prev').onclick=()=>turn(page-1);$('next').onclick=()=>turn(page+1);$('pages').onclick=e=>{if(e.target.dataset.page)turn(+e.target.dataset.page);};$('clear').onclick=()=>{resetSelection();updateSelection();};$('cart').onclick=showCart;$('close').onclick=()=>$('dialog').close();
$('dialogBody').onchange=e=>{if(e.target.dataset.variant===undefined)return;const i=+e.target.dataset.variant,row=cart[i],target=+e.target.value,p=products.find(p=>p.id===row.id);const other=cart.find((r,j)=>j!==i&&r.id===row.id&&r.variant===target);if(p.variants[target].stock<row.quantity+(other?other.quantity:0)){toast('目标规格库存不足');showCart();return;}if(other){other.quantity+=row.quantity;cart.splice(i,1);}else row.variant=target;showCart();};
$('dialogBody').onclick=e=>{if(e.target.dataset.remove===undefined)return;cart.splice(+e.target.dataset.remove,1);updateCartIndicator();showCart();};
$('mine').onclick=()=>{modal('我的',`<p>校园体验账号</p><p class="muted">买家交互原型 · 数据仅在当前页面保留</p><button id="resetDemo">重置演示数据</button>`);$('resetDemo').onclick=()=>{cart=[];keyword='';history=[];route='home';page=1;sort='default';resetSelection();updateCartIndicator();$('dialog').close();render();toast('演示数据已重置');};};render();

function updateCartIndicator(){const hasItems=cart.some(row=>row.quantity>0);$('cartIndicator').hidden=!hasItems;$('cart').setAttribute('aria-label',hasItems?'购物车，有商品':'购物车，空');}
