let stockLedger={},lifecycleAudit=[],demoClockOffset=0,nextProductId=10000;
function lifeNow(){return Date.now()+demoClockOffset;}
function ensureStock(){for(const p of products)p.variants.forEach((v,i)=>{const key=p.id+':'+i;if(!stockLedger[key])stockLedger[key]={available:v.stock,locked:0,sold:0};});}
function reflectStock(){for(const p of products)p.variants.forEach((v,i)=>{if(stockLedger[p.id+':'+i])v.stock=stockLedger[p.id+':'+i].available;});for(const p of createdProducts)if(p.productId)p.variants.forEach((v,i)=>{if(stockLedger[p.productId+':'+i])v.stock=String(stockLedger[p.productId+':'+i].available);});}
function reservePlacedOrders(orders){ensureStock();let stocks=structuredClone(stockLedger);const reserved=orders.map(o=>{o.createdAt=lifeNow();const x=LifecycleModel.reserve(o,stocks);stocks=x.stocks;return x.order;});stockLedger=stocks;orders.splice(0,orders.length,...reserved);reflectStock();lifecycleAudit.push('订单创建，占用库存：'+orders.map(o=>o.id).join('、'));}
function validatePending(ids){ensureStock();const active=new Set(products.map(p=>p.id));let stocks=stockLedger;demoOrders=demoOrders.map(o=>{if(!ids.includes(o.id)||o.createdAt===undefined)return o;const x=LifecycleModel.validate(o,stocks,active,lifeNow());stocks=x.stocks;if(JSON.stringify(x.order)!==JSON.stringify(o))lifecycleAudit.push(o.id+'：'+(x.order.notice||'状态更新'));return x.order;});stockLedger=stocks;reflectStock();}
const lifeWalletBase=walletTransaction;walletTransaction=function(ids,action,reason=''){if(action==='pay'){const before=ids.map(id=>demoOrders.find(o=>o.id===id)?.totalCents);validatePending(ids);if(ids.some((id,i)=>{const o=demoOrders.find(o=>o.id===id);return !o||o.status!=='待付款'||o.totalCents!==before[i];}))throw Error('订单商品或金额已变化，请返回订单页确认后再付款');}const originals=ids.map(id=>structuredClone(demoOrders.find(o=>o.id===id)));lifeWalletBase(ids,action,reason);for(const old of originals){const o=demoOrders.find(x=>x.id===old.id);if(old.createdAt===undefined)continue;if(action==='cancel'){const x=LifecycleModel.cancel(o,stockLedger);stockLedger=x.stocks;Object.assign(o,x.order);}if(action==='pay')for(const i of o.items)if(i.locked){stockLedger[i.sku].locked-=i.quantity;stockLedger[i.sku].sold+=i.quantity;i.locked=false;i.deducted=true;}if(action==='approve')for(const i of o.items)if(i.deducted){stockLedger[i.sku].available+=i.quantity;stockLedger[i.sku].sold-=i.quantity;i.deducted=false;}}reflectStock();};
const lifeItemsBase=orderItems;orderItems=function(o){const valid=o.items.filter(i=>!i.invalid),invalid=o.items.filter(i=>i.invalid);return (o.notice?`<p class="lifeNotice">${escapeHTML(o.notice)}</p>`:'')+lifeItemsBase({...o,items:valid})+(invalid.length?`<details class="invalidItems"><summary>${invalid.length} 项已失效，不参与结算</summary>${invalid.map(i=>`<p>${escapeHTML(i.name)} · ${escapeHTML(i.variant)} × ${i.quantity} · 已释放库存</p>`).join('')}</details>`:'')+(o.status==='待付款'&&o.createdAt!==undefined?`<p class="muted">剩余付款时间约 ${Math.max(0,Math.ceil((o.createdAt+1800000-lifeNow())/60000))} 分钟</p>`:'');};
const lifeOrdersBase=showOrders;showOrders=function(filter='全部'){validatePending(demoOrders.filter(o=>o.status==='待付款').map(o=>o.id));lifeOrdersBase(filter);$('dialogBody').querySelector('.orderBottom').insertAdjacentHTML('beforeend','<button id="advanceOrderClock">演示：推进 30 分钟</button>');$('advanceOrderClock').onclick=()=>{demoClockOffset+=1800000;expireOrders();showOrders('退款/已关闭');};};
const lifeDetailBase=orderDetail;orderDetail=function(id,seller){validatePending([id]);lifeDetailBase(id,seller);};const lifeActionBase=orderAction;orderAction=function(id,action,seller){if(action==='pay'){validatePending([id]);const o=demoOrders.find(o=>o.id===id);if(o.status!=='待付款'){showOrders();return;}}lifeActionBase(id,action,seller);if(action==='pay'){const o=demoOrders.find(o=>o.id===id);if(o.notice)$('orderError').textContent=o.notice;}};
const lifeGroupBase=showGroupPayment;showGroupPayment=function(group){validatePending(demoOrders.filter(o=>o.group===group).map(o=>o.id));lifeGroupBase(group);const notices=demoOrders.filter(o=>o.group===group&&o.notice).map(o=>o.notice);if(notices.length)$('groupPaymentError').textContent=[...new Set(notices)].join('；');};
function expireOrders(){const ids=demoOrders.filter(o=>o.status==='待付款'&&o.createdAt!==undefined&&lifeNow()-o.createdAt>=1800000).map(o=>o.id);if(!ids.length)return;validatePending(ids);toast('待付款订单已超时取消，库存已释放');}
setInterval(expireOrders,1000);
function removeFromSale(p,reason='店主主动下架'){p.status='已下架';p.offReason=reason;const index=products.findIndex(x=>x.editorId===p.id);if(index>=0){p.productId=products[index].id;cart=cart.filter(r=>r.id!==p.productId);products.splice(index,1);updateCartIndicator();}lifecycleAudit.push(p.name+'：'+reason);render();}
syncPublishedProduct=function(p){shops[0]=applicationData().name;if(p.deleted)return;if(p.status!=='在售'){removeFromSale(p,p.offReason);return;}if(!p.productId)p.productId=nextProductId++;const existing=products.find(x=>x.id===p.productId);if(existing)for(const row of cart.filter(r=>r.id===p.productId)){const old=existing.variants[row.variant],next=p.variants[row.variant];if(!next||old?.price!==Number(next.price)||row.quantity>Number(next.stock))row.reviewNeeded=true;}p.variants.forEach((v,i)=>{const key=p.productId+':'+i;stockLedger[key]={available:Number(v.stock),locked:stockLedger[key]?.locked||0,sold:stockLedger[key]?.sold||0};});const item={id:p.productId,editorId:p.id,name:p.name,description:p.description,shop:0,sales:existing?.sales||0,icon:'',bg:'#edf2e7',image:p.image,defaultVariant:p.defaultVariant,variants:p.variants.map(v=>({name:v.name,price:Number(v.price),stock:Number(v.stock)}))};if(existing)Object.assign(existing,item);else products.unshift(item);render();};
const lifeDrawBase=drawProductEditor;drawProductEditor=function(){lifeDrawBase();if(productDraft.status==='在售'){$('saveProductDraft').hidden=true;$('productEditor').querySelector('[type="submit"]').textContent='保存修改';}const hasOrders=demoOrders.some(o=>['待付款','待发货','待收货','退款审核中'].includes(o.status)&&o.items.some(i=>i.productId===productDraft.productId));if(hasOrders)document.querySelectorAll('[data-delete-spec]').forEach(b=>{b.disabled=true;b.title='有未完成订单时保留规格结构';});};
const lifeSaveBase=saveEditedProduct;saveEditedProduct=function(publish){if(createdProducts.find(p=>p.id===productDraft.id)?.deleted){toast('商品已删除，不可恢复');return;}const before=createdProducts.find(p=>p.id===productDraft.id);lifeSaveBase(publish||before?.status==='在售');if(!$('dialog').open)lifecycleAudit.push(productDraft.name+'：保存商品');};
managedProducts=function(filter='全部'){const rows=createdProducts.filter(p=>!p.deleted&&(filter==='全部'||p.status===filter));return rows.length?rows.map(p=>{const reason=LifecycleModel.deleteReason(p,demoOrders);const stocks=Object.entries(stockLedger).filter(([k])=>k.startsWith(p.productId+':')).map(([,v])=>v);return `<article class="managedProduct"><img src="assets/presets/${p.image||'box'}.svg" alt="商品图片"><div><b>${escapeHTML(p.name)}</b><p>${p.variants.length} 个规格 · ${escapeHTML(p.status)}${p.offReason?' · '+escapeHTML(p.offReason):''}</p><small>可售 ${p.variants.reduce((n,v)=>n+Number(v.stock||0),0)} · 锁定 ${stocks.reduce((n,v)=>n+v.locked,0)}</small>${reason?`<p class="muted">${reason}</p>`:''}</div><div class="lifeActions"><button data-edit-product="${p.id}">编辑</button>${p.status==='在售'?`<button data-life-off="${p.id}">下架</button>`:''}<button data-life-delete="${p.id}" ${reason?'disabled':''} title="${reason}">删除</button></div></article>`;}).join(''):'<div class="empty">暂无'+filter+'商品</div>';};
const lifeContentBase=sellerContent;sellerContent=function(section){if(section!=='products')return lifeContentBase(section);return `<div class="sellerActionBar"><span>商品资料与发布状态</span><div><button id="lifeSamples">载入下架演示</button><button data-seller-detail="import">Excel 批量导入</button><button data-seller-detail="create" class="primary">＋ 创建商品</button></div></div><section class="applicationCard"><div class="tabs">${['全部','草稿','在售','已下架'].map(s=>`<button data-managed-filter="${s}">${s}（${createdProducts.filter(p=>!p.deleted&&(s==='全部'||p.status===s)).length}）</button>`).join('')}</div><div id="managedList">${managedProducts()}</div></section><div class="lifeDemoBar"><button id="lifeBuyerOrders">查看买家订单</button><button id="lifeAudit">演示：查看历史与库存</button></div>`;};
sellerReviewPage.addEventListener('click',e=>{const off=e.target.closest('[data-life-off]'),del=e.target.closest('[data-life-delete]');if(off||del){const p=createdProducts.find(p=>p.id===(off?.dataset.lifeOff||del.dataset.lifeDelete));modal(off?'下架商品':'删除商品',`<h3>${escapeHTML(p.name)}</h3><p>${off?'下架后买家不能购买，购物车会移除该商品。待付款订单在查看或支付时校验，已付款订单继续履约。':'删除后不可恢复；历史订单、审计和库存记录仍保留。'}</p><div class="orderActions"><button id="lifeAbort">返回</button><button id="lifeConfirm" class="primary">确认${off?'下架':'删除'}</button></div>`);$('lifeAbort').onclick=()=>$('dialog').close();$('lifeConfirm').onclick=()=>{if(off)removeFromSale(p);else{const reason=LifecycleModel.deleteReason(p,demoOrders);if(reason){toast(reason);return;}p.deleted=true;lifecycleAudit.push(p.name+'：软删除，保留历史记录');}$('dialog').close();openSeller('products');};}if(e.target.closest('#lifeBuyerOrders'))showOrders();if(e.target.closest('#lifeSamples'))seedLifecycle();if(e.target.closest('#lifeAudit'))modal('演示：历史与库存',`<p class="muted">历史只读，无恢复入口</p>${createdProducts.filter(p=>p.deleted).map(p=>`<p>已删除：${escapeHTML(p.name)}</p>`).join('')}<pre>${escapeHTML(JSON.stringify(stockLedger,null,2))}</pre>${lifecycleAudit.map(s=>`<p>${escapeHTML(s)}</p>`).join('')}`);});
function seedLifecycle(){if(createdProducts.some(p=>p.id==='life-a')){toast('演示已经载入');return;}for(const [id,name,price] of [['life-a','演示记事本','20'],['life-b','演示文具盒','30']]){const p={id,name,description:'商品下架与订单校验演示',image:id==='life-a'?'book':'box',category:'ordinary',status:'在售',variants:[{name:'标准款',price,stock:'10'}],defaultVariant:0};createdProducts.push(p);syncPublishedProduct(p);}const rows=createdProducts.filter(p=>['life-a','life-b'].includes(p.id)).map(p=>({id:p.productId,variant:0,quantity:1}));const orders=OrderModel.create(rows,products,'LIFE'+Date.now());reservePlacedOrders(orders);demoOrders.unshift(...orders);openSeller('products');toast('已生成包含两件商品的待付款订单，可下架其中一件后查看买家订单');}
const lifeMineBase=showMine;showMine=function(){lifeMineBase();const reset=$('resetDemo').onclick;$('resetDemo').onclick=()=>{stockLedger={};lifecycleAudit=[];demoClockOffset=0;reset();};};$('mine').onclick=showMine;
if(location.hash==='#seller-products')showSeller('products');

const lifeCheckoutBase=showCheckout;showCheckout=function(){ensureStock();let changed=false;cart=cart.filter(r=>{if(r.checked===false)return true;const p=products.find(p=>p.id===r.id),v=p?.variants[r.variant];if(!v||v.stock<=0){changed=true;return false;}if(r.reviewNeeded||r.quantity>v.stock){changed=true;r.quantity=Math.min(r.quantity,v.stock);r.reviewNeeded=false;}return true;});updateCartIndicator();if(changed){modal('请确认购物车变化','<p>商品价格或库存已变化，数量已按当前可购买库存调整，失效商品已移除。请查看最新金额后重新结算。</p><button id="lifeReviewCart" class="primary">查看购物车</button>');$('lifeReviewCart').onclick=showCart;return;}lifeCheckoutBase();};
