// Shared in-memory orders for buyer and seller previews.
let demoOrders=[],orderFilter='全部',orderSeller=null;
const orderTabs=['全部','待付款','待发货','待收货','已完成','退款/已关闭'];
const orderModalBase=modal;
modal=function(title,html){$('dialog').classList.remove('ordersDialog');orderModalBase(title,html);};
function orderItems(o){return o.items.map(i=>`<div class="orderLine"><span><b>${escapeHTML(i.name)}</b><small>${escapeHTML(i.variant)} × ${i.quantity}</small></span><strong>${money(i.cents*i.quantity/100)}</strong></div>`).join('');}
function orderButtons(o,seller){const choices=seller?(o.status==='待发货'?[['ship','发货']]:o.status==='退款审核中'?[['approve','同意退款（模拟）'],['reject','驳回退款']]:[]):(o.status==='待付款'?[['pay','余额付款'],['cancel','取消订单']]:o.status==='待发货'?[['request','申请整单退款']]:o.status==='待收货'?[['receive','确认收货']]:[]);return choices.map(([a,t])=>`<button data-order-action="${a}" data-order-id="${o.id}" class="${a==='cancel'||a==='reject'?'':'primary'}">${t}</button>`).join('');}
function orderCard(o,seller=false){return `<article class="orderCard"><div class="orderCardHead"><b>${escapeHTML(shops[o.shop])}</b><span class="tag">${o.status}</span></div><p class="muted">订单 ${o.id}${seller?' · 买家昵称：'+o.nickname:''}</p>${orderItems(o)}${o.reason?`<p class="orderReason">退款驳回原因：${escapeHTML(o.reason)}</p>`:''}<div class="orderActions"><strong>合计 ${money(o.totalCents/100)}</strong><div><button data-order-detail="${o.id}">查看详情</button>${orderButtons(o,seller)}</div></div></article>`;}
function matchesOrder(o,filter){return filter==='全部'||(filter==='退款/已关闭'?['退款审核中','已退款','已取消'].includes(o.status):o.status===filter);}
showOrders=function(filter='全部'){orderSeller=null;orderFilter=filter;const rows=demoOrders.filter(o=>matchesOrder(o,filter));modal('我的订单',`<div class="orderTopNote"><span>按店铺查看每一笔订单</span><span class="demo">模拟交易</span></div><div class="tabs orderTabs">${orderTabs.map(t=>`<button data-order-filter="${t}" class="${t===filter?'active':''}">${t}</button>`).join('')}</div><div class="orderList">${rows.length?rows.map(o=>orderCard(o)).join(''):'<div class="empty"><h3>暂无'+(filter==='全部'?'':filter)+'订单</h3><p>从购物车提交订单，或载入示例体验完整流程。</p></div>'}</div><div class="orderBottom"><button id="orderAccount">返回我的</button><button id="orderSeed">载入示例订单</button><button id="orderSellerPreview">店主处理预览 →</button></div>`);$('dialog').classList.add('ordersDialog');document.querySelectorAll('[data-order-filter]').forEach(b=>b.onclick=()=>showOrders(b.dataset.orderFilter));$('orderAccount').onclick=showMine;$('orderSeed').onclick=seedOrders;$('orderSellerPreview').onclick=()=>showSellerOrders();bindOrders($('dialogBody'),false);};
function bindOrders(root,seller){root.querySelectorAll('[data-order-action]').forEach(b=>b.onclick=()=>orderAction(b.dataset.orderId,b.dataset.orderAction,seller));root.querySelectorAll('[data-order-detail]').forEach(b=>b.onclick=()=>orderDetail(b.dataset.orderDetail,seller));}
function orderDetail(id,seller){const o=demoOrders.find(o=>o.id===id);modal('订单详情',`<p class="muted">订单 ${o.id} · ${escapeHTML(shops[o.shop])}</p><h2>${o.status}</h2>${seller?'<p>买家昵称：校园买家</p>':''}${orderItems(o)}<h3>合计 ${money(o.totalCents/100)}</h3><div class="orderHistory">${o.events.map(e=>`<p>• ${escapeHTML(e)}</p>`).join('')}</div><div class="orderActions"><button id="ordersBack">返回订单列表</button><div>${orderButtons(o,seller)}</div></div>`);$('ordersBack').onclick=()=>seller?showSellerOrders(orderSeller):showOrders(orderFilter);bindOrders($('dialogBody'),seller);}
function orderAction(id,action,seller){const o=demoOrders.find(o=>o.id===id);const labels={pay:'余额付款',cancel:'取消订单',request:'申请整单退款',approve:'同意整单退款（模拟）',reject:'驳回退款',ship:'确认发货',receive:'确认收货'};modal(labels[action],`<p>${escapeHTML(shops[o.shop])} · ${money(o.totalCents/100)}</p><p>${action==='receive'?'确认收货后，订单将标记为已完成。':action==='request'?'整笔店铺订单进入退款审核，审核期间暂停发货。':action==='approve'?'全额退回买家虚拟余额后，该订单关闭。':'确认执行本次操作。'}</p>${action==='pay'?`<p>可用虚拟余额 ${money((virtualWallet.balances.buyer||0)/100)}</p>`:''}${action==='reject'?'<label>驳回原因<textarea id="refundReason" maxlength="200" placeholder="请填写原因"></textarea></label>':''}<p id="orderError" role="alert"></p><div class="orderActions"><button id="abortOrderAction">返回</button><button class="primary" id="confirmOrderAction">确认</button></div>`);$('abortOrderAction').onclick=()=>seller?showSellerOrders(orderSeller):showOrders(orderFilter);$('confirmOrderAction').onclick=()=>{try{walletTransaction([id],action,$('refundReason')?.value||'');seller?showSellerOrders(orderSeller):showOrders('全部');toast('订单状态已更新');}catch(e){walletPaymentError($('orderError'),e,()=>orderAction(id,action,seller));}};}
showCheckout=function(){const rows=cart.filter(r=>r.checked!==false);if(!rows.length)return;let preview;try{preview=OrderModel.create(rows,products,'预览');}catch(e){toast(e.message);return;}modal('确认结算',`<p>本次将生成 ${preview.length} 笔店铺订单</p>${preview.map(o=>`<section class="orderCard"><h3>${escapeHTML(shops[o.shop])}</h3>${orderItems(o)}</section>`).join('')}<h3>合计 ${money(preview.reduce((n,o)=>n+o.totalCents,0)/100)}</h3><p>账户余额：<strong id="walletBalance"></strong></p><p class="muted">提交后可统一余额付款，也可在订单中逐笔付款。使用平台虚拟余额付款。</p><div class="orderActions"><button id="checkoutBack">返回购物车</button><button id="submitOrders" class="primary">提交订单</button></div>`);$('checkoutBack').onclick=showCart;loadBalance();$('submitOrders').onclick=()=>{try{const orders=OrderModel.create(rows,products,'D'+Date.now());reservePlacedOrders(orders);demoOrders.unshift(...orders);cart=cart.filter(r=>!rows.includes(r));updateCartIndicator();showGroupPayment(orders[0].group);}catch(e){toast(e.message);}};};
function showGroupPayment(group){const rows=demoOrders.filter(o=>o.group===group&&o.status==='待付款');modal('订单提交成功',`<span class="tag">待付款</span><h2>${rows.length} 笔店铺订单已生成</h2><p>统一支付金额 <strong>${money(rows.reduce((n,o)=>n+o.totalCents,0)/100)}</strong></p><p class="muted">此操作仅余额付款成功，不扣除真实账户余额。</p><div class="orderActions"><button id="payLater">稍后付款</button><button class="primary" id="payGroup">统一余额付款</button></div>`);$('payLater').onclick=()=>showOrders('待付款');$('payGroup').onclick=()=>{demoOrders=demoOrders.map(o=>o.group===group&&o.status==='待付款'?OrderModel.move(o,'pay'):o);showOrders('待发货');};}
function showSellerOrders(shop=orderSeller??0){orderSeller=Number(shop);modal('店主订单处理',`<div class="orderTopNote"><label>预览店铺 <select id="orderShop">${shops.map((s,i)=>`<option value="${i}" ${i===orderSeller?'selected':''}>${escapeHTML(s)}</option>`).join('')}</select></label><span class="demo">模拟店主</span></div><div class="orderList">${demoOrders.filter(o=>o.shop===orderSeller&&o.status!=='待付款'&&o.status!=='已取消').map(o=>orderCard(o,true)).join('')||'<div class="empty">暂无已付款订单</div>'}</div><div class="orderBottom"><button id="backBuyerOrders">返回买家订单</button></div>`);$('dialog').classList.add('ordersDialog');$('orderShop').onchange=e=>showSellerOrders(+e.target.value);$('backBuyerOrders').onclick=()=>showOrders();bindOrders($('dialogBody'),true);}
function seedOrders(){if(demoOrders.some(o=>o.group==='SAMPLE')){toast('示例订单已载入');return;}const states=['待付款','待发货','待收货','已完成','退款审核中','已退款','已取消'];const samples=states.map((status,i)=>{const p=products[i+1];const o=OrderModel.create([{id:p.id,variant:0,quantity:1}],products,'SAMPLE')[0];return {...o,id:'示例-'+(i+1),status,events:['示例订单',status]};});demoOrders.unshift(...samples);showOrders();}
const orderMineBase=showMine;showMine=function(){orderMineBase();const reset=$('resetDemo').onclick;$('resetDemo').onclick=()=>{demoOrders=[];reset();};};$('mine').onclick=showMine;
const orderSellerContent=sellerContent;sellerContent=function(section){if(section==='orders')return '<section class="applicationCard"><h2>店铺订单</h2><p>处理已付款订单和退款申请。</p><button id="openOrderManager" class="primary">打开订单管理</button></section>';return orderSellerContent(section);};
sellerReviewPage.addEventListener('click',e=>{if(e.target.closest('#openOrderManager'))showSellerOrders();});
