let createdProducts=[],productDraft=null,qualificationRecord=null;
const presetNames={book:'图书',pen:'文具',cup:'杯子',bag:'布包',shirt:'服装',box:'收纳用品'};
function qualifiedNow(){return qualificationRecord?.status==='已通过'&&qualificationRecord.expiry>=new Date().toLocaleDateString('sv-SE');}
function editorRead(){productDraft.name=$('editName').value;productDraft.description=$('editDescription').value;productDraft.category=$('editCategory').value;productDraft.image=document.querySelector('[name="presetImage"]:checked')?.value||'';productDraft.variants=[...document.querySelectorAll('.editVariant')].map(r=>({name:r.querySelector('[data-field="name"]').value,price:r.querySelector('[data-field="price"]').value,stock:r.querySelector('[data-field="stock"]').value}));productDraft.defaultVariant=Number(document.querySelector('[name="defaultSpec"]:checked')?.value??-1);}
function openProductEditor(id){productDraft=id?structuredClone(createdProducts.find(p=>p.id===id)):{id:'P'+Date.now(),name:'',description:'',category:'',image:'',variants:[{name:'标准款',price:'',stock:''}],defaultVariant:0,status:'草稿'};drawProductEditor();}
function drawProductEditor(){const p=productDraft;modal(p.status==='在售'?'编辑商品':'创建 / 编辑商品草稿',`<form id="productEditor" novalidate><div class="editorScroll"><section class="editorSection"><span class="eyebrow">01 / 基本信息</span><label>商品名称<input id="editName" value="${escapeHTML(p.name)}" placeholder="填写名称即可保存草稿"></label><label>商品介绍<textarea id="editDescription" placeholder="介绍商品的用途和特点">${escapeHTML(p.description)}</textarea></label><h3>选择商品封面</h3><div class="presetGrid">${ProductEditorModel.images.map(id=>`<label class="presetOption"><input type="radio" name="presetImage" value="${id}" ${p.image===id?'checked':''}><img src="assets/presets/${id}.svg" alt="${presetNames[id]}"><span>${presetNames[id]}</span><small>${id}</small></label>`).join('')}</div><p class="muted">图片随客户端提供，保存图片编号即可。</p></section><section class="editorSection"><span class="eyebrow">02 / 准入类目</span><label>经营准入<select id="editCategory"><option value="">请选择</option><option value="ordinary" ${p.category==='ordinary'?'selected':''}>普通白名单商品</option><option value="licensed" ${p.category==='licensed'?'selected':''}>专项许可类目（演示）</option></select></label><p id="categoryHint"></p><button type="button" id="editorQualification" hidden>申请专项资质</button></section><section class="editorSection"><span class="eyebrow">03 / 规格与库存</span><div class="variantTable"><div class="variantHeading"><span>默认</span><span>规格名称</span><span>价格（元）</span><span>库存</span><span>操作</span></div>${p.variants.map((v,i)=>`<div class="editVariant"><input type="radio" name="defaultSpec" aria-label="规格 ${i+1} 设为默认" value="${i}" ${i===p.defaultVariant?'checked':''}><input aria-label="规格 ${i+1} 名称" data-field="name" value="${escapeHTML(v.name)}"><input aria-label="规格 ${i+1} 价格" data-field="price" inputmode="decimal" value="${escapeHTML(v.price)}"><input aria-label="规格 ${i+1} 库存" data-field="stock" inputmode="numeric" value="${escapeHTML(v.stock)}"><button type="button" data-delete-spec="${i}" ${p.variants.length===1?'disabled':''}>删除</button></div>`).join('')}</div><button type="button" id="addSpec">＋ 添加规格</button><p class="muted">默认规格用于买家快捷加入购物车。库存为 0 时展示缺货。</p></section><div id="editorErrors" role="alert"></div></div><div class="editorFooter"><button type="button" id="exitEditor">返回商品管理</button><div><button type="button" id="saveProductDraft">保存草稿</button><button type="submit" class="primary">上架</button></div></div></form>`);$('dialog').classList.add('productEditorDialog');
 function hint(){const locked=$('editCategory').value==='licensed'&&!qualifiedNow();$('categoryHint').textContent=$('editCategory').value==='ordinary'?'主体资质已通过模拟审核，可上架普通商品。':locked?'该类目尚未解锁，可以保存草稿，需通过专项资质审核后上架。':$('editCategory').value?'专项资质有效，可以上架。':'请选择商品所属准入类目。';$('editorQualification').hidden=!locked;}
 $('editCategory').onchange=hint;hint();$('editorQualification').onclick=()=>{editorRead();showQualificationForm(true);};$('addSpec').onclick=()=>{editorRead();productDraft.variants.push({name:'',price:'',stock:''});drawProductEditor();};document.querySelectorAll('[data-delete-spec]').forEach(b=>b.onclick=()=>{editorRead();const i=+b.dataset.deleteSpec;productDraft.variants.splice(i,1);if(productDraft.defaultVariant===i)productDraft.defaultVariant=0;else if(productDraft.defaultVariant>i)productDraft.defaultVariant--;drawProductEditor();});$('exitEditor').onclick=()=>{$('dialog').close();openSeller('products');};$('saveProductDraft').onclick=()=>saveEditedProduct(false);$('productEditor').onsubmit=e=>{e.preventDefault();saveEditedProduct(true);};}
function saveEditedProduct(publish){editorRead();const errors=ProductEditorModel.errors(productDraft,publish,qualifiedNow());if(errors.length){$('editorErrors').innerHTML='<h3>请检查以下内容</h3><ul>'+errors.map(e=>`<li>${escapeHTML(e)}</li>`).join('')+'</ul>';$('editorErrors').scrollIntoView({block:'nearest'});return;}const p=structuredClone(productDraft);p.status=publish?'在售':'草稿';const i=createdProducts.findIndex(x=>x.id===p.id);if(i<0)createdProducts.push(p);else createdProducts[i]=p;syncPublishedProduct(p);$('dialog').close();openSeller('products');toast(publish?'商品已上架，可返回买家页面查看':'草稿已保存');}
function syncPublishedProduct(p){shops[0]=applicationData().name;const existing=products.find(x=>x.editorId===p.id);if(p.status!=='在售'){if(existing){cart=cart.filter(r=>r.id!==existing.id);updateCartIndicator();products.splice(products.indexOf(existing),1);render();}return;}const v=p.variants.map(x=>({name:x.name,price:Number(x.price),stock:Number(x.stock)}));const item={id:existing?.id||Math.max(...products.map(x=>x.id))+1,editorId:p.id,name:p.name,description:p.description,shop:0,sales:0,icon:'',bg:'#edf2e7',image:p.image,defaultVariant:p.defaultVariant,variants:v};if(existing)Object.assign(existing,item);else products.unshift(item);render();}
function managedProducts(filter='全部'){const rows=createdProducts.filter(p=>filter==='全部'||p.status===filter);return rows.length?rows.map(p=>`<article class="managedProduct"><img src="assets/presets/${p.image||'box'}.svg" alt="${p.image?'商品封面':'待选图片'}"><div><b>${escapeHTML(p.name)}</b><p>${p.variants.length} 个规格 · ${p.image?'已选择封面':'待选择封面'}</p></div><span class="tag">${p.status}</span><button data-edit-product="${p.id}">编辑</button></article>`).join(''):'<div class="empty">暂无'+filter+'商品，点击“创建商品”开始。</div>';}
const editorContentBase=sellerContent;sellerContent=function(section){if(section==='products')return `<div class="sellerActionBar"><span>商品资料与发布状态</span><div><button data-seller-detail="import">Excel 批量导入</button><button data-seller-detail="create" class="primary">＋ 创建商品</button></div></div><section class="applicationCard"><div class="tabs">${['全部','草稿','在售'].map(s=>`<button data-managed-filter="${s}">${s}（${createdProducts.filter(p=>s==='全部'||p.status===s).length}）</button>`).join('')}</div><div id="managedList">${managedProducts()}</div></section>`;if(section==='qualifications')return `<section class="applicationCard"><span class="tag">模拟审核</span><h2>主体资质</h2><p>主体：${escapeHTML(applicationData().subject||'校园示例主体')}</p><p>营业执照编号：${escapeHTML(applicationData().license)}</p></section><section class="applicationCard sellerSpaced"><h2>专项资质</h2><p>${qualificationRecord?escapeHTML(qualificationRecord.type)+' · '+qualificationRecord.status:'暂无申请'}</p><button data-seller-detail="qualification">${qualificationRecord?'查看专项资质':'申请专项资质'}</button></section>`;return editorContentBase(section);};
sellerReviewPage.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-product]');if(edit)openProductEditor(edit.dataset.editProduct);const filter=e.target.closest('[data-managed-filter]');if(filter){$('managedList').innerHTML=managedProducts(filter.dataset.managedFilter);sellerReviewPage.querySelectorAll('[data-managed-filter]').forEach(b=>b.classList.toggle('active',b===filter));}});
const editorDetailBase=sellerDetail;sellerDetail=function(kind){if(kind==='create')openProductEditor();else if(kind==='qualification')showQualificationForm(false);else editorDetailBase(kind);};
const editorModalBase=modal;modal=function(title,html){$('dialog').classList.remove('productEditorDialog');editorModalBase(title,html);};
const editorCardBase=card;card=function(p){if(!p.editorId)return editorCardBase(p);const v=p.variants[p.defaultVariant];return `<article class="product" data-id="${p.id}" tabindex="0" aria-label="${escapeHTML(p.name)}" aria-selected="false"><span class="tick">✓</span><div class="art"><img src="assets/presets/${p.image}.svg" alt="${escapeHTML(p.name)}" style="height:100%;width:100%;object-fit:contain"></div><div class="info"><h3>${escapeHTML(p.name)}</h3><button class="shopLink" data-store="0">${escapeHTML(shops[0])} ↗</button><div class="bottom"><span class="price">${money(v.price)}</span><span class="sales">已售 0</span></div><div class="variant">${escapeHTML(v.name)}${v.stock===0?' · 缺货':''}</div></div></article>`;};
const editorProductDetailBase=showProductDetail;showProductDetail=function(p){editorProductDetailBase(p);if(p.editorId){$('dialogBody').querySelector('.art').innerHTML=`<img src="assets/presets/${p.image}.svg" alt="商品封面" style="height:100%">`;}};
const editorMineBase=showMine;showMine=function(){editorMineBase();const reset=$('resetDemo').onclick;$('resetDemo').onclick=()=>{createdProducts=[];qualificationRecord=null;for(let i=products.length-1;i>=0;i--)if(products[i].editorId)products.splice(i,1);reset();};};$('mine').onclick=showMine;

if(location.hash.startsWith("#seller-"))showSeller(location.hash.slice(8));
