// Local evidence remains in this page only; no files are uploaded.
let demoReports=[],reportFiles=[],reportTarget=null,reportFilter='全部';
function clearReportDraft(){reportFiles.forEach(f=>URL.revokeObjectURL(f.url));reportFiles=[];}
const reportModalBase=modal;modal=function(title,html){clearReportDraft();$('dialog').classList.remove('reportsDialog');reportModalBase(title,html);};
$('dialog').addEventListener('close',clearReportDraft);
function reportForm(target){reportTarget=target;modal('提交举报',`<section class="reportTarget"><span class="tag">${target.kind==='product'?'商品举报':'店铺举报'}</span><h3>${escapeHTML(target.name)}</h3><p>${escapeHTML(shops[target.shop])}</p></section><form id="reportForm"><label class="reportField">举报原因<select id="reportReason" required><option value="">请选择原因</option>${ReportModel.reasons.map(r=>`<option>${r}</option>`).join('')}</select></label><label class="reportField">举报说明<textarea id="reportText" required placeholder="请描述你发现的问题，方便管理员核实"></textarea></label><p id="reportError" class="reportError" role="alert"></p><div class="orderActions"><button type="button" id="reportCancel">返回</button><button class="primary" type="submit" id="reportSubmit">提交举报</button></div></form>`);
 $('reportCancel').onclick=()=>{if(target.kind==='product')showProductDetail(products.find(p=>p.id===target.id));else $('dialog').close();};
 $('reportForm').onsubmit=e=>{e.preventDefault();try{const reason=$('reportReason').value,description=$('reportText').value;ReportModel.validate(reason,description,reportFiles.map(f=>f.file));const record={id:'R'+Date.now(),target:{...target},reason,description:description.trim(),status:'待处理',createdAt:new Date().toLocaleString('zh-CN'),images:reportFiles.map(f=>({name:f.file.name,url:f.url})),result:''};reportFiles=[];demoReports.unshift(record);modal('举报已提交',`<div class="reportSuccess"><span>✓</span><h2>已收到你的举报</h2><p>管理员将核实相关内容，处理结果可在“我的举报”查看。</p><p class="muted">举报编号 ${record.id}</p></div><div class="orderActions"><button id="reportDone">继续浏览</button><button class="primary" id="reportTrack">查看举报进度</button></div>`);$('reportDone').onclick=()=>$('dialog').close();$('reportTrack').onclick=()=>reportDetail(record.id);}catch(err){$('reportError').textContent=err.message;}};
}
function renderReportImages(){const root=$('reportPreviews');root.innerHTML=reportFiles.map((f,i)=>`<figure><button type="button" data-preview-image="${i}" aria-label="预览图片 ${i+1}"><img src="${f.url}" alt="${escapeHTML(f.file.name)}"></button><figcaption>${escapeHTML(f.file.name)}</figcaption><button type="button" data-remove-image="${i}">删除</button></figure>`).join('');root.querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{URL.revokeObjectURL(reportFiles[+b.dataset.removeImage].url);reportFiles.splice(+b.dataset.removeImage,1);renderReportImages();});root.querySelectorAll('[data-preview-image]').forEach(b=>b.onclick=()=>previewEvidence(reportFiles[+b.dataset.previewImage].url));}
function previewEvidence(url){const d=document.createElement('dialog');d.className='evidenceViewer';d.innerHTML=`<button aria-label="关闭图片预览">关闭</button><img src="${url}" alt="举报证据预览">`;document.body.append(d);d.querySelector('button').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();}
function showReports(filter='全部'){reportFilter=filter;const rows=demoReports.filter(r=>filter==='全部'||r.status===filter);modal('我的举报',`<p>查看举报进度与管理员的处理结果</p><div class="tabs">${['全部','待处理','已处理'].map(s=>`<button data-report-filter="${s}" class="${s===filter?'active':''}">${s}</button>`).join('')}</div><div class="reportList">${rows.length?rows.map(r=>`<article class="orderCard"><div class="orderCardHead"><b>${escapeHTML(r.target.name)}</b><span class="tag">${r.status}</span></div><p>${escapeHTML(r.reason)}</p><p class="muted">${r.createdAt} · ${r.target.kind==='product'?'商品举报':'店铺举报'}</p><div class="orderActions"><span>文字举报</span><button data-report-detail="${r.id}">查看详情 →</button></div></article>`).join(''):'<div class="empty"><h3>暂无举报记录</h3><p>可从商品详情或店铺页面提交举报。</p></div>'}</div><div class="orderBottom"><button id="reportsAccount">返回我的</button><span class="muted">举报人身份不向卖家展示</span></div>`);$('dialog').classList.add('reportsDialog');document.querySelectorAll('[data-report-filter]').forEach(b=>b.onclick=()=>showReports(b.dataset.reportFilter));document.querySelectorAll('[data-report-detail]').forEach(b=>b.onclick=()=>reportDetail(b.dataset.reportDetail));$('reportsAccount').onclick=showMine;}
function reportDetail(id){const r=demoReports.find(r=>r.id===id);modal('举报详情',`<span class="tag">${r.status}</span><h2>${escapeHTML(r.target.name)}</h2><p>${escapeHTML(shops[r.target.shop])}</p><p class="muted">${r.id} · ${r.createdAt}</p><section class="reportTarget"><h3>${escapeHTML(r.reason)}</h3><p class="reportDescription">${escapeHTML(r.description)}</p></section><div class="reportImages">${r.images.map((f,i)=>`<figure><button data-evidence="${i}"><img src="${f.url}" alt="${escapeHTML(f.name)}"></button><figcaption>${escapeHTML(f.name)}</figcaption></figure>`).join('')}</div><section class="reportResult"><h3>${r.status==='已处理'?'处理结果':'等待管理员处理'}</h3><p class="reportDescription">${r.status==='已处理'?escapeHTML(r.result):'处理完成后，结果说明将在这里显示。'}</p>${r.resolvedAt?`<p class="muted">${r.resolvedAt}</p>`:''}</section><div class="orderActions"><button id="reportListBack">返回我的举报</button>${r.status==='待处理'?'<button id="simulateReport">模拟管理员处理</button>':''}</div>`);$('reportListBack').onclick=()=>showReports(reportFilter);document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>previewEvidence(r.images[+b.dataset.evidence].url));if($('simulateReport'))$('simulateReport').onclick=()=>resolveReport(id);}
function resolveReport(id){modal('模拟管理员处理',`<p class="muted">此入口用于预览举报结果，不执行实际店铺处罚。</p><label class="reportField">处理结果说明<textarea id="reportResolution" placeholder="例如：经核实，已对店铺发出警告。" required></textarea></label><p class="reportError" id="resolutionError" role="alert"></p><div class="orderActions"><button id="resolutionBack">返回</button><button id="resolutionConfirm" class="primary">完成处理（模拟）</button></div>`);$('resolutionBack').onclick=()=>reportDetail(id);$('resolutionConfirm').onclick=()=>{try{demoReports=demoReports.map(r=>r.id===id?ReportModel.resolve(r,$('reportResolution').value):r);reportDetail(id);}catch(e){$('resolutionError').textContent=e.message;}};}
const reportProductBase=showProductDetail;showProductDetail=function(p){reportProductBase(p);$('dialogBody').insertAdjacentHTML('beforeend','<div class="reportEntry"><button id="reportProduct">举报商品</button></div>');$('reportProduct').onclick=()=>reportForm({kind:'product',id:p.id,shop:p.shop,name:p.name});};
const reportRenderBase=render;render=function(){reportRenderBase();$('reportStore')?.remove();if(route==='store'){$('subtitle').insertAdjacentHTML('afterend','<button id="reportStore">举报店铺</button>');$('reportStore').onclick=()=>reportForm({kind:'shop',id:storeId,shop:storeId,name:shops[storeId]});}};
const reportMineBase=showMine;showMine=function(){reportMineBase();$('dialogBody').insertAdjacentHTML('beforeend','<div class="accountEntries"><button id="myReports"><span><strong>我的举报</strong><small>查看处理进度与结果</small></span><span>→</span></button></div>');$('myReports').onclick=()=>showReports();const reset=$('resetDemo').onclick;$('resetDemo').onclick=()=>{demoReports.forEach(r=>r.images.forEach(f=>URL.revokeObjectURL(f.url)));demoReports=[];reset();};};$('mine').onclick=showMine;render();
