// Reviewable seller pages use a separate demo identity, not a real approval.
let sellerPreview=false;
const sellerSections={overview:'店铺概览',products:'商品管理',orders:'订单管理',qualifications:'经营资质',settings:'店铺设置'};
const sellerDescriptions={overview:'从这里开始，打理你的校园小店。',products:'管理草稿与在售商品，让好物被更多人发现。',orders:'查看订单进度，安排每一笔订单的履约。',qualifications:'查看主体资质与可经营范围。',settings:'维护店铺资料，查看平台通知。'};
const sellerReviewPage=document.createElement('section');sellerReviewPage.id='sellerReviewPage';sellerReviewPage.hidden=true;document.body.append(sellerReviewPage);
const sellerDemoProducts=[{name:'方格手账本',icon:'📒',price:19,status:'草稿',stock:20},{name:'帆布日常托特包',icon:'👜',price:26,status:'草稿',stock:15}];
function sellerReviewRail(active){return `<aside class="previewRail sellerRail"><b>页面预览</b><nav><button data-stage="submitted">提交成功</button><button data-stage="pending">等待审核</button><button data-stage="approved" class="${active==='approved'?'active':''}">审核通过</button><button data-stage="seller" class="${active==='seller'?'active':''}">店主工作台</button></nav><span class="reviewState">布局待确认 · 模拟店主</span><button id="leaveSellerPreview">返回买家</button></aside>`;}
function prepareSeller(){if($('dialog').open)$('dialog').close();applicationPage.hidden=true;document.querySelector('.app').hidden=true;sellerReviewPage.hidden=false;}
function bindSellerRail(){sellerReviewPage.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{
 if(b.dataset.stage==='seller')openSeller('overview');else if(b.dataset.stage==='approved')openApproved();else {sellerReviewPage.hidden=true;openApplicationPage(b.dataset.stage);}
 });$('leaveSellerPreview').onclick=leaveSeller;}
function leaveSeller(){sellerReviewPage.hidden=true;applicationPage.hidden=true;document.querySelector('.app').hidden=false;window.history.replaceState(null,'',location.pathname+location.search);}
function openApproved(){location.hash='application-approved';showApproved();}
function showApproved(){prepareSeller();sellerPreview=true;const data=applicationData();
 sellerReviewPage.innerHTML=sellerReviewRail('approved')+`<header class="applicationHeader"><strong>校园集 <span>/ 开店申请</span></strong><span>校园体验账号</span></header><div class="applicationScroll"><div class="applicationContainer"><ol class="applicationSteps"><li class="done"><b>✓</b>提交申请</li><li class="done"><b>✓</b>平台审核</li><li class="current"><b>✓</b>开店完成</li></ol><section class="submittedHero"><div class="applicationSymbol">✓</div><span class="stateLabel">审核通过</span><h1>开店成功，欢迎成为店主</h1><p>你的店铺已准备就绪，可以开始创建第一件商品。</p></section><section class="applicationCard submittedCard"><div class="approvedStore"><span>店铺名称</span><h2>${escapeHTML(data.name)}</h2><span class="tag">主体资质模拟审核通过</span><span class="tag">正常营业</span></div><p class="applicationNote">普通商品可直接经营。发布许可管控类目商品前，请先在“经营资质”中申请专项资质。</p></section><div class="applicationActions centered"><button id="approvedToMine">返回我的</button><button class="primary" id="enterSeller">进入店铺管理 →</button></div><p class="applicationFootnote">APP-03 · 审核通过页 · 待确认</p></div></div>`;
 bindSellerRail();$('enterSeller').onclick=()=>openSeller('overview');$('approvedToMine').onclick=()=>{leaveSeller();showMine();};
}
function openSeller(section){location.hash='seller-'+section;showSeller(section);}
function showSeller(section){if(!sellerSections[section])section='overview';prepareSeller();sellerPreview=true;
 sellerReviewPage.innerHTML=sellerReviewRail('seller')+`<div class="sellerShell"><aside class="sellerSidebar"><div class="sellerIdentity"><span class="storeMonogram">青</span><h2>${escapeHTML(applicationData().name)}</h2><span class="tag">正常营业</span></div><nav>${Object.entries(sellerSections).map(([id,label],i)=>`<button data-section="${id}" class="${section===id?'active':''}"><span>0${i+1}</span>${label}<span>›</span></button>`).join('')}</nav><div class="sellerSideFoot">店主工作台<br><span>校园集 · CAMPUS MARKET</span></div></aside><div class="sellerMain"><header class="sellerTop"><span>我的店铺 / ${sellerSections[section]}</span><button id="sellerAccount">我的账户 ↗</button></header><div class="sellerScroll"><div class="sellerHeading"><div><span class="eyebrow">SELLER WORKSPACE</span><h1>${sellerSections[section]}</h1><p>${sellerDescriptions[section]}</p></div><span class="demo">模拟数据</span></div><div id="sellerContent">${sellerContent(section)}</div><p class="applicationFootnote">SELLER-01 · ${sellerSections[section]} · 页面布局待确认</p></div></div></div>`;
 bindSellerRail();sellerReviewPage.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>openSeller(b.dataset.section));$('sellerAccount').onclick=()=>{leaveSeller();showMine();};
 sellerReviewPage.querySelectorAll('[data-seller-detail]').forEach(b=>b.onclick=()=>sellerDetail(b.dataset.sellerDetail));
 sellerReviewPage.querySelectorAll('[data-product-filter]').forEach(b=>b.onclick=()=>{sellerReviewPage.querySelectorAll('[data-product-filter]').forEach(x=>x.classList.toggle('active',x===b));$('sellerProductList').innerHTML=productRows(b.dataset.productFilter);bindProductDetails();});bindProductDetails();
}
function productRows(filter='全部'){const rows=sellerDemoProducts.filter(p=>filter==='全部'||p.status===filter);return rows.length?rows.map((p,i)=>`<div class="sellerProductRow"><span class="sellerProductIcon">${p.icon}</span><div><b>${p.name}</b><p>默认规格：标准款</p></div><strong>¥${p.price.toFixed(2)}</strong><span>库存 ${p.stock}</span><span class="tag">${p.status}</span><button data-product-detail="${sellerDemoProducts.indexOf(p)}">查看草稿</button></div>`).join(''):'<div class="empty">暂无'+filter+'商品</div>';}
function bindProductDetails(){sellerReviewPage.querySelectorAll('[data-product-detail]').forEach(b=>b.onclick=()=>{const p=sellerDemoProducts[+b.dataset.productDetail];modal('商品草稿',`<div class="balanceCard"><h2>${p.icon} ${p.name}</h2><p>默认规格：标准款</p><p>价格：¥${p.price.toFixed(2)} · 库存：${p.stock}</p><p>状态：草稿</p></div><p class="muted">当前展示草稿详情布局，编辑及上架交互将在商品管理设计中展开。</p>`);});}
function sellerContent(section){
 if(section==='overview')return `<div class="sellerMetrics">${[['待处理订单','0','orders'],['在售商品','0','products'],['商品草稿','2','products'],['主体资质','已通过','qualifications']].map(([label,value,dest])=>`<button data-section="${dest}"><span>${label}</span><strong>${value}</strong><small>查看详情 →</small></button>`).join('')}</div><section class="applicationCard sellerWelcome"><div><span class="stateLabel">开始经营</span><h2>让第一件好物，遇见它的新主人</h2><p>单个创建商品，或通过 Excel 导入后完善草稿。</p></div><button class="primary" data-section="products">管理商品 →</button></section><div class="sellerTwoColumns"><section class="applicationCard"><h2>待办事项</h2><button class="sellerTask" data-section="products"><span>完善商品草稿</span><b>2 →</b></button><button class="sellerTask" data-section="qualifications"><span>查看经营资质</span><b>→</b></button></section><section class="applicationCard"><h2>店铺通知</h2><p class="stateLabel">开店申请已通过</p><p>主体资质模拟审核完成，店铺处于正常营业状态。</p><p class="muted">暂无警告或停业通知</p></section></div>`;
 if(section==='products')return `<div class="sellerActionBar"><span>商品资料与发布状态</span><div><button data-seller-detail="import">Excel 批量导入</button><button class="primary" data-seller-detail="create">＋ 创建商品</button></div></div><section class="applicationCard"><div class="tabs"><button class="active" data-product-filter="全部">全部</button><button data-product-filter="草稿">草稿（2）</button><button data-product-filter="在售">在售（0）</button></div><div id="sellerProductList">${productRows()}</div></section>`;
 if(section==='orders')return `<section class="applicationCard"><h2>店铺订单</h2><div class="empty"><h3>暂时还没有订单</h3><p>已付款订单将在这里展示，供你安排履约。</p></div></section>`;
 if(section==='qualifications')return `<section class="applicationCard"><div class="sellerActionBar"><h2>主体资质</h2><span class="tag">已通过</span></div><dl class="applicationFacts"><div><dt>店铺</dt><dd>${escapeHTML(applicationData().name)}</dd></div><div><dt>营业执照</dt><dd>${escapeHTML(applicationData().license)}</dd></div></dl></section><section class="applicationCard sellerSpaced"><div class="sellerActionBar"><h2>专项资质</h2><button data-seller-detail="qualification">申请专项资质 →</button></div><p>普通白名单商品可直接经营；许可类目须通过相应专项资质审核。</p><div class="empty">暂无专项资质申请</div></section>`;
 return `<section class="applicationCard"><div class="sellerActionBar"><h2>店铺资料</h2><button data-seller-detail="settings">查看资料字段</button></div><dl class="applicationFacts"><div><dt>店铺名称</dt><dd>${escapeHTML(applicationData().name)}</dd></div><div><dt>营业状态</dt><dd><span class="tag">正常营业</span></dd></div><div><dt>店铺简介</dt><dd>校园里的生活好物小店。</dd></div></dl></section><section class="applicationCard sellerSpaced"><h2>警告与营业通知</h2><p>暂无警告或停业记录。</p></section>`;
}
function sellerDetail(kind){const details={create:['单个创建商品','商品名称、图片、准入类目、规格、价格、库存及默认规格将在创建页面维护。保存为草稿，上架时校验图片及经营资质。'],import:['Excel 批量导入','上传文件 → 后端逐行校验 → 预览有效行及错误报告 → 确认导入草稿 → 选择预置图片并上架。'],qualification:['申请专项资质','选择拟经营类目，填写资质类型、证件编号及有效期，等待管理员审核。'],settings:['店铺资料','店铺名称、简介及资料修改的表单将在下一步设计中展开。']};const [title,text]=details[kind];modal(title,`<span class="tag">交互设计待展开</span><p style="line-height:1.9;margin-top:18px">${text}</p><p class="muted">本轮用于确认店主工作台的栏目与页面结构。</p>`);}
const originalApplicationPage=showApplicationPage;
showApplicationPage=function(kind){if(kind==='approved'){showApproved();return;}sellerReviewPage.hidden=true;originalApplicationPage(kind);const nav=applicationPage.querySelector('.previewRail nav');nav.insertAdjacentHTML('beforeend','<button id="previewApproved">APP-03 审核通过</button><button id="previewSeller">店主工作台</button>');$('previewApproved').onclick=openApproved;$('previewSeller').onclick=()=>openSeller('overview');};
const sellerMine=showMine;
showMine=function(){sellerMine();if(sellerPreview||shopApplication?.status==='APPROVED'){const entry=$('applyShop');entry.innerHTML=`<span><strong>${SellerModel.accountEntry('APPROVED')}</strong><small>进入店铺管理 · 模拟店主</small></span><span>→</span>`;entry.onclick=()=>openSeller('overview');}const reset=$('resetDemo').onclick;$('resetDemo').onclick=()=>{sellerPreview=false;reset();};};$('mine').onclick=showMine;
function sellerHash(){if(location.hash==='#application-approved')showApproved();else if(location.hash.startsWith('#seller-'))showSeller(location.hash.slice(8));else sellerReviewPage.hidden=true;}
window.addEventListener('hashchange',sellerHash);
if(location.hash==='#application-approved'||location.hash.startsWith('#seller-'))sellerHash();else if(['#application-submitted','#application-pending'].includes(location.hash))showApplicationPage(location.hash.slice(13));
