package edu.seu.vcampus.client.course.service;
import edu.seu.vcampus.common.course.*; import edu.seu.vcampus.common.error.ErrorDetail; import edu.seu.vcampus.common.protocol.*; import org.junit.jupiter.api.Test;
import javax.swing.SwingUtilities; import java.io.Serializable; import java.time.Duration; import java.util.*; import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
class CourseClientServiceTest {
 @Test void sendsExactTypedCommandAndReturnsTypedData(){ RecordingTransport t=new RecordingTransport(); EnrollmentView view=new EnrollmentView("e","o","s","NORMAL","ACTIVE",java.time.Instant.EPOCH,null,0);t.next=CompletableFuture.completedFuture(ResponseBody.success(view));CourseClientService c=new CourseClientService(t);assertThat(c.enroll(new EnrollCommand("o")).join()).isEqualTo(view);assertThat(t.command).isEqualTo("COURSE_ENROLL");assertThat(t.body).isInstanceOf(EnrollCommand.class);assertThat(t.timeout).isEqualTo(Duration.ofSeconds(15)); }
 @Test void mapsFailureToStableUserExceptionWithoutLosingRetryMetadata(){RecordingTransport t=new RecordingTransport();t.next=CompletableFuture.completedFuture(ResponseBody.failure("COURSE_OFFERING_FULL","容量已满",new ErrorDetail("COURSE_OFFERING_FULL","容量已满",Map.of(),"trace",false)));CourseClientException e=catchThrowableOfType(()->new CourseClientService(t).enroll(new EnrollCommand("o")).join(),CompletionException.class).getCause() instanceof CourseClientException ce?ce:null;assertThat(e).isNotNull();assertThat(e.code()).isEqualTo("COURSE_OFFERING_FULL");assertThat(e.traceId()).isEqualTo("trace");}
 @Test void edtCallReturnsImmediatelyWithoutJoiningTransportFuture() throws Exception {RecordingTransport t=new RecordingTransport();t.next=new CompletableFuture<>();CourseClientService c=new CourseClientService(t);CompletableFuture<?>[] result=new CompletableFuture<?>[1];SwingUtilities.invokeAndWait(()->result[0]=c.searchOfferings(new OfferingSearchQuery(null,null,null,false,0,20)));assertThat(result[0]).isNotDone();}
 @Test void productionConnectionAdapterInvokesBlockingSendOffEdtAndKeepsLaterEventsResponsive() throws Exception {
  CountDownLatch sendEntered=new CountDownLatch(1),releaseSend=new CountDownLatch(1),laterEvent=new CountDownLatch(1);
  CourseClientService service=new CourseClientService(new BlockingTransport(sendEntered,releaseSend));
  try {
   SwingUtilities.invokeLater(service::listTerms);
   assertThat(sendEntered.await(1,TimeUnit.SECONDS)).isTrue();
   SwingUtilities.invokeLater(laterEvent::countDown);
   assertThat(laterEvent.await(300,TimeUnit.MILLISECONDS)).isTrue();
  } finally { releaseSend.countDown(); }
 }
 @Test void exposesAdminQueriesWithExactCommandsAndAcceptsAnySerializableList(){RecordingTransport t=new RecordingTransport();CourseClientService c=new CourseClientService(t);t.next=CompletableFuture.completedFuture(ResponseBody.success(new LinkedList<TermView>()));assertThat(c.listTerms().join()).isEmpty();assertThat(t.command).isEqualTo("COURSE_TERM_LIST");assertThat(t.body).isSameAs(EmptyRequest.INSTANCE);t.next=CompletableFuture.completedFuture(ResponseBody.success(new edu.seu.vcampus.common.paging.PageResult<CourseView>(List.of(),0,20,0)));assertThat(c.searchCatalog(new CourseCatalogQuery(null,null,0,20)).join().items()).isEmpty();assertThat(t.command).isEqualTo("COURSE_CATALOG_SEARCH");t.next=CompletableFuture.completedFuture(ResponseBody.success(new edu.seu.vcampus.common.paging.PageResult<AdjustmentAuditView>(List.of(),0,20,0)));c.searchAdjustmentAudits(new AdjustmentAuditQuery(null,null,null,null,0,20)).join();assertThat(t.command).isEqualTo("COURSE_ADJUSTMENT_AUDIT_SEARCH");}
 @Test void getsAuthoritativeCurrentTermWithExactCommand(){RecordingTransport t=new RecordingTransport();TermView term=new TermView("current","2026-1","当前学期",java.time.LocalDate.of(2026,9,1),java.time.LocalDate.of(2027,1,1),java.time.Instant.EPOCH,java.time.Instant.EPOCH.plusSeconds(1),java.time.Instant.EPOCH.plusSeconds(2),java.time.Instant.EPOCH.plusSeconds(3),"ACTIVE",0,java.time.Instant.EPOCH,java.time.Instant.EPOCH);t.next=CompletableFuture.completedFuture(ResponseBody.success(term));CourseClientService c=new CourseClientService(t);assertThat(c.getCurrentTerm().join()).isEqualTo(term);assertThat(t.command).isEqualTo("COURSE_GET_CURRENT_TERM");assertThat(t.body).isSameAs(EmptyRequest.INSTANCE);}
 @Test void mapsTransportAndMalformedResponsesAtFacadeBoundary(){RecordingTransport t=new RecordingTransport();CourseClientService c=new CourseClientService(t);t.next=CompletableFuture.failedFuture(new java.io.IOException("socket"));assertClientCode(()->c.getCurrentSchedule().join(),"COMMON_NETWORK_ERROR");t.next=CompletableFuture.completedFuture(ResponseBody.success(null));assertClientCode(()->c.getCurrentSchedule().join(),"COMMON_PROTOCOL_ERROR");t.next=CompletableFuture.completedFuture(ResponseBody.success("wrong"));assertClientCode(()->c.getCurrentSchedule().join(),"COMMON_PROTOCOL_ERROR");t.next=CompletableFuture.completedFuture(new ResponseBody<>(false,null,null,null,null));assertClientCode(()->c.getCurrentSchedule().join(),"COMMON_PROTOCOL_ERROR");}
 @Test void mapsDirectAndWrappedTimeoutSeparatelyFromNetwork(){RecordingTransport t=new RecordingTransport();CourseClientService c=new CourseClientService(t);t.next=CompletableFuture.failedFuture(new TimeoutException("late"));assertClientFailure(()->c.listTerms().join(),"COMMON_TIMEOUT","请求超时，请稍后重试",true);t.next=CompletableFuture.failedFuture(new CompletionException(new ExecutionException(new TimeoutException("late"))));assertClientFailure(()->c.listTerms().join(),"COMMON_TIMEOUT","请求超时，请稍后重试",true);}
 @Test void authenticationFailureThrownSynchronouslyPreservesItsCodeAndNotifiesOnce(){RecordingTransport t=new RecordingTransport();CourseClientException expected=new CourseClientException("AUTH_SESSION_EXPIRED","expired","trace",false);t.thrown=expected;CourseClientService c=new CourseClientService(t);List<CourseClientException> notifications=new ArrayList<>();c.addAuthenticationFailureListener(notifications::add);assertClientCode(()->c.listTerms().join(),"AUTH_SESSION_EXPIRED");assertThat(notifications).containsExactly(expected);}
 @org.junit.jupiter.params.ParameterizedTest
 @org.junit.jupiter.params.provider.ValueSource(strings={"AUTH_SESSION_EXPIRED","AUTH_ACCOUNT_DISABLED","AUTH_INITIAL_PASSWORD_CHANGE_REQUIRED"})
 void wrappedAuthenticationFuturePreservesItsCodeAndNotifiesOnce(String code){RecordingTransport t=new RecordingTransport();CourseClientException expected=new CourseClientException(code,"authentication failed","trace",false);t.next=CompletableFuture.failedFuture(new CompletionException(new ExecutionException(expected)));CourseClientService c=new CourseClientService(t);List<CourseClientException> notifications=new ArrayList<>();c.addAuthenticationFailureListener(notifications::add);assertClientCode(()->c.listTerms().join(),code);assertThat(notifications).containsExactly(expected);}
 @Test void nonAuthenticationAndNetworkFailuresKeepTheExistingNetworkMappingAndNeverNotifyAuthenticationListeners(){RecordingTransport t=new RecordingTransport();CourseClientService c=new CourseClientService(t);List<CourseClientException> notifications=new ArrayList<>();c.addAuthenticationFailureListener(notifications::add);t.next=CompletableFuture.failedFuture(new CourseClientException("COURSE_TERM_CLOSED","closed",null,false));assertClientCode(()->c.listTerms().join(),"COMMON_NETWORK_ERROR");t.next=CompletableFuture.failedFuture(new java.io.IOException("socket"));assertClientCode(()->c.listTerms().join(),"COMMON_NETWORK_ERROR");assertThat(notifications).isEmpty();}
 private static void assertClientCode(org.assertj.core.api.ThrowableAssert.ThrowingCallable action,String code){Throwable failure=catchThrowable(action);while(failure instanceof CompletionException&&failure.getCause()!=null)failure=failure.getCause();assertThat(failure).isInstanceOf(CourseClientException.class);assertThat(((CourseClientException)failure).code()).isEqualTo(code);}
 private static void assertClientFailure(org.assertj.core.api.ThrowableAssert.ThrowingCallable action,String code,String message,boolean retryable){Throwable f=catchThrowable(action);while(f instanceof CompletionException&&f.getCause()!=null)f=f.getCause();assertThat(f).isInstanceOf(CourseClientException.class);CourseClientException e=(CourseClientException)f;assertThat(e.code()).isEqualTo(code);assertThat(e.getMessage()).isEqualTo(message);assertThat(e.retryable()).isEqualTo(retryable);}
 private static final class RecordingTransport implements CourseTransport {String command;Serializable body;Duration timeout;RuntimeException thrown;CompletableFuture<? extends ResponseBody<? extends Serializable>> next;@SuppressWarnings("unchecked") public <T extends Serializable> CompletableFuture<ResponseBody<T>> send(String c,Serializable b,Duration d){command=c;body=b;timeout=d;if(thrown!=null)throw thrown;return (CompletableFuture<ResponseBody<T>>)(CompletableFuture<?>)next;}}
 private record BlockingTransport(CountDownLatch entered,CountDownLatch release) implements CourseTransport {
  @SuppressWarnings("unchecked") public <T extends Serializable> CompletableFuture<ResponseBody<T>> send(String c,Serializable b,Duration d){entered.countDown();try{if(!release.await(2,TimeUnit.SECONDS))throw new IllegalStateException("send was not released");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException(e);}return (CompletableFuture<ResponseBody<T>>)(CompletableFuture<?>)CompletableFuture.completedFuture(ResponseBody.success(new LinkedList<TermView>()));}
 }
}
