package edu.seu.vcampus.client.course.service;
import edu.seu.vcampus.common.course.*; import edu.seu.vcampus.common.error.ErrorDetail; import edu.seu.vcampus.common.protocol.*; import org.junit.jupiter.api.Test;
import javax.swing.SwingUtilities; import java.io.Serializable; import java.time.Duration; import java.util.*; import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
class CourseClientServiceTest {
 @Test void sendsExactTypedCommandAndReturnsTypedData(){ RecordingTransport t=new RecordingTransport(); EnrollmentView view=new EnrollmentView("e","o","s","NORMAL","ACTIVE",java.time.Instant.EPOCH,null,0);t.next=CompletableFuture.completedFuture(ResponseBody.success(view));CourseClientService c=new CourseClientService(t);assertThat(c.enroll(new EnrollCommand("o")).join()).isEqualTo(view);assertThat(t.command).isEqualTo("COURSE_ENROLL");assertThat(t.body).isInstanceOf(EnrollCommand.class);assertThat(t.timeout).isEqualTo(Duration.ofSeconds(15)); }
 @Test void mapsFailureToStableUserExceptionWithoutLosingRetryMetadata(){RecordingTransport t=new RecordingTransport();t.next=CompletableFuture.completedFuture(ResponseBody.failure("COURSE_OFFERING_FULL","容量已满",new ErrorDetail("COURSE_OFFERING_FULL","容量已满",Map.of(),"trace",false)));CourseClientException e=catchThrowableOfType(()->new CourseClientService(t).enroll(new EnrollCommand("o")).join(),CompletionException.class).getCause() instanceof CourseClientException ce?ce:null;assertThat(e).isNotNull();assertThat(e.code()).isEqualTo("COURSE_OFFERING_FULL");assertThat(e.traceId()).isEqualTo("trace");}
 @Test void edtCallReturnsImmediatelyWithoutJoiningTransportFuture() throws Exception {RecordingTransport t=new RecordingTransport();t.next=new CompletableFuture<>();CourseClientService c=new CourseClientService(t);CompletableFuture<?>[] result=new CompletableFuture<?>[1];SwingUtilities.invokeAndWait(()->result[0]=c.searchOfferings(new OfferingSearchQuery(null,null,null,false,0,20)));assertThat(result[0]).isNotDone();}
 private static final class RecordingTransport implements CourseTransport {String command;Serializable body;Duration timeout;CompletableFuture<? extends ResponseBody<? extends Serializable>> next;@SuppressWarnings("unchecked") public <T extends Serializable> CompletableFuture<ResponseBody<T>> send(String c,Serializable b,Duration d){command=c;body=b;timeout=d;return (CompletableFuture<ResponseBody<T>>)(CompletableFuture<?>)next;}}
}
