package edu.seu.vcampus.common.shop;

/** Stable public error symbols for every shop workflow. */
public enum ShopErrorCode {
    SHOP_SELLER_APPLICATION_EXISTS,
    SHOP_SELLER_APPLICATION_STATUS_INVALID,
    SHOP_SELLER_NOT_APPROVED,
    SHOP_CATEGORY_INVALID,
    SHOP_NOT_FOUND,
    SHOP_NOT_OWNER,
    SHOP_SUSPENDED,
    SHOP_STATUS_INVALID,
    SHOP_PRODUCT_INACTIVE,
    SHOP_PRODUCT_NAME_EXISTS,
    SHOP_COVER_IMAGE_URL_INVALID,
    SHOP_SKU_UNAVAILABLE,
    SHOP_PRICE_FILTER_INVALID,
    SHOP_PRICE_CHANGED,
    SHOP_INSUFFICIENT_STOCK,
    SHOP_CART_EMPTY,
    SHOP_ORDER_STATUS_INVALID,
    SHOP_ORDER_NOT_OWNED,
    SHOP_BUYER_FORBIDDEN,
    SHOP_SELF_PURCHASE_FORBIDDEN,
    PAYMENT_ALREADY_COMPLETED,
    PAYMENT_NOT_PENDING,
    PAYMENT_AMOUNT_MISMATCH
}
